// Single source of truth for frontend config.
// Reads values from window.__BDCHQ_CONFIG__, which is populated by
// runtime-config.js (generated by `npm run config:build` from .env).
//
// Previously the inline <script> in every HTML <head> duplicated defaults
// AND hardcoded project URLs per page. That's been removed — values now
// come only from runtime-config.js.

const runtimeConfig =
  (typeof window !== "undefined" && window.__BDCHQ_CONFIG__) || {};

let warnedOnce = false;

function warnIfDev(missing) {
  if (warnedOnce) return;
  warnedOnce = true;
  if (runtimeConfig.appEnv === "development" && missing.length > 0) {
    console.warn(
      "[bdchq config] missing:", missing.join(", "),
      "\nRun `npm run config:build` after filling .env."
    );
  }
}

export function getPublicConfig() {
  const cfg = {
    appEnv: runtimeConfig.appEnv || "development",
    appUrl:
      runtimeConfig.appUrl ||
      (typeof window !== "undefined" ? window.location.origin : ""),
    supabaseUrl: runtimeConfig.supabaseUrl || "",
    supabaseAnonKey: runtimeConfig.supabaseAnonKey || "",
    stripePublishableKey: runtimeConfig.stripePublishableKey || "",
    posthogKey: runtimeConfig.posthogKey || "",
    posthogHost: runtimeConfig.posthogHost || "https://us.i.posthog.com",
    sentryDsn: runtimeConfig.sentryDsn || "",
    sentryTracesSampleRate: runtimeConfig.sentryTracesSampleRate || "0.05",
    turnstileSiteKey: runtimeConfig.turnstileSiteKey || "",
    environment: runtimeConfig.appEnv || "development",
  };
  return cfg;
}

export function missingConfigKeys() {
  const cfg = getPublicConfig();
  const missing = [];
  if (!cfg.supabaseUrl) missing.push("PUBLIC_SUPABASE_URL");
  if (!cfg.supabaseAnonKey) missing.push("PUBLIC_SUPABASE_ANON_KEY");
  warnIfDev(missing);
  return missing;
}
